---
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "install process started"
      - npm install
  build:
    commands:
      - echo "build process started"
      - npm ci
      - npm install -g serverless@3.34.0
  post_build:
    commands:
      - echo "build process finished, Updating lambda Function..."
      - echo "Updating lambda Function..."
      - echo "Deploying with stage:$stage"
      - sls deploy --stage $stage --verbose
      - echo "Deployment is DONE!!"
artifacts:
  files:
    - "**/*"
    - dist/**/*
    - node_modules/**/*
    - package.json
    - package-lock.json



# ---
# version: 0.2
# phases:
#   install:
#     runtime-versions:
#       nodejs: 14
#     commands:
#         - echo "install process started"
#         - npm install -g serverless@3.34.0
#   build:
#     commands:
#       - echo "build process started"
#       - npm run ci
#   post_build:
#     commands:
#       - echo "build process finished, Updating lambda Function..."
#       - echo "Updating lambda Function..."
#       - sls deploy --stage $stage
#       - echo "DONE!!"
# artifacts:
#   files:
#     - "**/*"
#     - dist/**/*
#     - node_modules/**/*
#     - package.json
#     - package-lock.json


# version: 0.2
# phases:
#   install:
#     runtime-versions:
#         nodejs: 14
#         commands:
#           - echo install process started
#           - npm install -g serverless@3.34.0
#   build:
#     commands:
#       - echo build process started
#       - npm ci
#       # - zip -r9 ./deploy.zip .
#       # - npm install -g serverless@3.34.0
#   post_build:
#     commands:
#       - echo build process finished, "Updating lambda Function..."
#       - echo "Updating lambda Function..."
#       - sls deploy --stage $stage
#       # - aws lambda update-function-code --function-name aws-sls-employee-api-dev-api --zip-file fileb://deploy.zip
#       - echo "DONE!!"

# artifacts:
#   files:
#     - '**/*'
#     - 'dist/**/*'
#     - 'node_modules**/*'
#     - 'package.json'
#     - 'package-lock.json'

      
# version: 0.2
# phases:
#   install:
#     runtime-versions:
#       nodejs: 14
#   build:
#     commands:
#       - npm ci
#       # - zip -r9 ./deploy.zip .
#       - npm install -g serverless@3.34.0
#   post_build:
#     commands:
#       - echo "Updating lambda Function..."
#       - sls deploy --stage $stage
#       # - aws lambda update-function-code --function-name aws-sls-employee-api-dev-api --zip-file fileb://deploy.zip
#       - echo "DONE!!"
